import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display} from "next/font/google";
import Footer from "@/src/app/components/Footer";
import "./globals.css";
import { Providers } from "./providers";
import ClientLayout from "./client-layout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-title-display",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Miz Mosaics - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}
      >
        <Providers>
          <ClientLayout>
            {children}
          </ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
